name: CI Pipeline for FastAPI project

on:
  pull_request:
    branches:
      - main  # Run tests on PRs to main

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: pytest
